// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_simulation_sizelimit_cpp
List run_simulation_sizelimit_cpp(NumericVector zr_w_dist, NumericVector month_weights, NumericMatrix W1_alk, NumericMatrix agedata, List harvest_params_in, List growth_params_dd_in1, List growth_params_dd_in2, List survival_params, List scenario_to_run, DataFrame policy_combos, DataFrame compliance_structure, int before_policy_years, int policy_years, double lake_area_ha, int initial_pop_size, double rec_a, double rec_b, double rec_v, double F_over_Z_ratio, double juv_onlyM_len, int spawn_month, int recruit_entry_month, int rep, double vmonthly_avg, double min_adult_age, double age_recruit, double age_spawn, double psd_stock, double psd_quality, double psd_preferred, double psd_memorable, double psd_trophy, bool Fagemode, bool use_ricker, int T_safe);
RcppExport SEXP _craibm_run_simulation_sizelimit_cpp(SEXP zr_w_distSEXP, SEXP month_weightsSEXP, SEXP W1_alkSEXP, SEXP agedataSEXP, SEXP harvest_params_inSEXP, SEXP growth_params_dd_in1SEXP, SEXP growth_params_dd_in2SEXP, SEXP survival_paramsSEXP, SEXP scenario_to_runSEXP, SEXP policy_combosSEXP, SEXP compliance_structureSEXP, SEXP before_policy_yearsSEXP, SEXP policy_yearsSEXP, SEXP lake_area_haSEXP, SEXP initial_pop_sizeSEXP, SEXP rec_aSEXP, SEXP rec_bSEXP, SEXP rec_vSEXP, SEXP F_over_Z_ratioSEXP, SEXP juv_onlyM_lenSEXP, SEXP spawn_monthSEXP, SEXP recruit_entry_monthSEXP, SEXP repSEXP, SEXP vmonthly_avgSEXP, SEXP min_adult_ageSEXP, SEXP age_recruitSEXP, SEXP age_spawnSEXP, SEXP psd_stockSEXP, SEXP psd_qualitySEXP, SEXP psd_preferredSEXP, SEXP psd_memorableSEXP, SEXP psd_trophySEXP, SEXP FagemodeSEXP, SEXP use_rickerSEXP, SEXP T_safeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type zr_w_dist(zr_w_distSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type month_weights(month_weightsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W1_alk(W1_alkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type agedata(agedataSEXP);
    Rcpp::traits::input_parameter< List >::type harvest_params_in(harvest_params_inSEXP);
    Rcpp::traits::input_parameter< List >::type growth_params_dd_in1(growth_params_dd_in1SEXP);
    Rcpp::traits::input_parameter< List >::type growth_params_dd_in2(growth_params_dd_in2SEXP);
    Rcpp::traits::input_parameter< List >::type survival_params(survival_paramsSEXP);
    Rcpp::traits::input_parameter< List >::type scenario_to_run(scenario_to_runSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type policy_combos(policy_combosSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type compliance_structure(compliance_structureSEXP);
    Rcpp::traits::input_parameter< int >::type before_policy_years(before_policy_yearsSEXP);
    Rcpp::traits::input_parameter< int >::type policy_years(policy_yearsSEXP);
    Rcpp::traits::input_parameter< double >::type lake_area_ha(lake_area_haSEXP);
    Rcpp::traits::input_parameter< int >::type initial_pop_size(initial_pop_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type rec_a(rec_aSEXP);
    Rcpp::traits::input_parameter< double >::type rec_b(rec_bSEXP);
    Rcpp::traits::input_parameter< double >::type rec_v(rec_vSEXP);
    Rcpp::traits::input_parameter< double >::type F_over_Z_ratio(F_over_Z_ratioSEXP);
    Rcpp::traits::input_parameter< double >::type juv_onlyM_len(juv_onlyM_lenSEXP);
    Rcpp::traits::input_parameter< int >::type spawn_month(spawn_monthSEXP);
    Rcpp::traits::input_parameter< int >::type recruit_entry_month(recruit_entry_monthSEXP);
    Rcpp::traits::input_parameter< int >::type rep(repSEXP);
    Rcpp::traits::input_parameter< double >::type vmonthly_avg(vmonthly_avgSEXP);
    Rcpp::traits::input_parameter< double >::type min_adult_age(min_adult_ageSEXP);
    Rcpp::traits::input_parameter< double >::type age_recruit(age_recruitSEXP);
    Rcpp::traits::input_parameter< double >::type age_spawn(age_spawnSEXP);
    Rcpp::traits::input_parameter< double >::type psd_stock(psd_stockSEXP);
    Rcpp::traits::input_parameter< double >::type psd_quality(psd_qualitySEXP);
    Rcpp::traits::input_parameter< double >::type psd_preferred(psd_preferredSEXP);
    Rcpp::traits::input_parameter< double >::type psd_memorable(psd_memorableSEXP);
    Rcpp::traits::input_parameter< double >::type psd_trophy(psd_trophySEXP);
    Rcpp::traits::input_parameter< bool >::type Fagemode(FagemodeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ricker(use_rickerSEXP);
    Rcpp::traits::input_parameter< int >::type T_safe(T_safeSEXP);
    rcpp_result_gen = Rcpp::wrap(run_simulation_sizelimit_cpp(zr_w_dist, month_weights, W1_alk, agedata, harvest_params_in, growth_params_dd_in1, growth_params_dd_in2, survival_params, scenario_to_run, policy_combos, compliance_structure, before_policy_years, policy_years, lake_area_ha, initial_pop_size, rec_a, rec_b, rec_v, F_over_Z_ratio, juv_onlyM_len, spawn_month, recruit_entry_month, rep, vmonthly_avg, min_adult_age, age_recruit, age_spawn, psd_stock, psd_quality, psd_preferred, psd_memorable, psd_trophy, Fagemode, use_ricker, T_safe));
    return rcpp_result_gen;
END_RCPP
}
// detect_gpu_info
List detect_gpu_info();
RcppExport SEXP _craibm_detect_gpu_info() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(detect_gpu_info());
    return rcpp_result_gen;
END_RCPP
}
// detect_openmp_info
List detect_openmp_info();
RcppExport SEXP _craibm_detect_openmp_info() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(detect_openmp_info());
    return rcpp_result_gen;
END_RCPP
}
// run_simulation_gpu
List run_simulation_gpu(NumericVector zr_w_dist, NumericVector month_weights, NumericMatrix W1_alk, NumericMatrix agedata, List harvest_params_in, List growth_params_dd_in1, List growth_params_dd_in2, List survival_params, List scenario_to_run, DataFrame policy_combos, DataFrame compliance_structure, int before_policy_years, int policy_years, double lake_area_ha, int initial_pop_size, double rec_a, double rec_b, double rec_v, double F_over_Z_ratio, double juv_onlyM_len, int spawn_month, int recruit_entry_month, int rep, double vmonthly_avg, double min_adult_age, double age_recruit, double age_spawn, double psd_stock, double psd_quality, double psd_preferred, double psd_memorable, double psd_trophy, bool Fagemode, bool use_ricker, int T_safe, int gpu_threads);
RcppExport SEXP _craibm_run_simulation_gpu(SEXP zr_w_distSEXP, SEXP month_weightsSEXP, SEXP W1_alkSEXP, SEXP agedataSEXP, SEXP harvest_params_inSEXP, SEXP growth_params_dd_in1SEXP, SEXP growth_params_dd_in2SEXP, SEXP survival_paramsSEXP, SEXP scenario_to_runSEXP, SEXP policy_combosSEXP, SEXP compliance_structureSEXP, SEXP before_policy_yearsSEXP, SEXP policy_yearsSEXP, SEXP lake_area_haSEXP, SEXP initial_pop_sizeSEXP, SEXP rec_aSEXP, SEXP rec_bSEXP, SEXP rec_vSEXP, SEXP F_over_Z_ratioSEXP, SEXP juv_onlyM_lenSEXP, SEXP spawn_monthSEXP, SEXP recruit_entry_monthSEXP, SEXP repSEXP, SEXP vmonthly_avgSEXP, SEXP min_adult_ageSEXP, SEXP age_recruitSEXP, SEXP age_spawnSEXP, SEXP psd_stockSEXP, SEXP psd_qualitySEXP, SEXP psd_preferredSEXP, SEXP psd_memorableSEXP, SEXP psd_trophySEXP, SEXP FagemodeSEXP, SEXP use_rickerSEXP, SEXP T_safeSEXP, SEXP gpu_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type zr_w_dist(zr_w_distSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type month_weights(month_weightsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W1_alk(W1_alkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type agedata(agedataSEXP);
    Rcpp::traits::input_parameter< List >::type harvest_params_in(harvest_params_inSEXP);
    Rcpp::traits::input_parameter< List >::type growth_params_dd_in1(growth_params_dd_in1SEXP);
    Rcpp::traits::input_parameter< List >::type growth_params_dd_in2(growth_params_dd_in2SEXP);
    Rcpp::traits::input_parameter< List >::type survival_params(survival_paramsSEXP);
    Rcpp::traits::input_parameter< List >::type scenario_to_run(scenario_to_runSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type policy_combos(policy_combosSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type compliance_structure(compliance_structureSEXP);
    Rcpp::traits::input_parameter< int >::type before_policy_years(before_policy_yearsSEXP);
    Rcpp::traits::input_parameter< int >::type policy_years(policy_yearsSEXP);
    Rcpp::traits::input_parameter< double >::type lake_area_ha(lake_area_haSEXP);
    Rcpp::traits::input_parameter< int >::type initial_pop_size(initial_pop_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type rec_a(rec_aSEXP);
    Rcpp::traits::input_parameter< double >::type rec_b(rec_bSEXP);
    Rcpp::traits::input_parameter< double >::type rec_v(rec_vSEXP);
    Rcpp::traits::input_parameter< double >::type F_over_Z_ratio(F_over_Z_ratioSEXP);
    Rcpp::traits::input_parameter< double >::type juv_onlyM_len(juv_onlyM_lenSEXP);
    Rcpp::traits::input_parameter< int >::type spawn_month(spawn_monthSEXP);
    Rcpp::traits::input_parameter< int >::type recruit_entry_month(recruit_entry_monthSEXP);
    Rcpp::traits::input_parameter< int >::type rep(repSEXP);
    Rcpp::traits::input_parameter< double >::type vmonthly_avg(vmonthly_avgSEXP);
    Rcpp::traits::input_parameter< double >::type min_adult_age(min_adult_ageSEXP);
    Rcpp::traits::input_parameter< double >::type age_recruit(age_recruitSEXP);
    Rcpp::traits::input_parameter< double >::type age_spawn(age_spawnSEXP);
    Rcpp::traits::input_parameter< double >::type psd_stock(psd_stockSEXP);
    Rcpp::traits::input_parameter< double >::type psd_quality(psd_qualitySEXP);
    Rcpp::traits::input_parameter< double >::type psd_preferred(psd_preferredSEXP);
    Rcpp::traits::input_parameter< double >::type psd_memorable(psd_memorableSEXP);
    Rcpp::traits::input_parameter< double >::type psd_trophy(psd_trophySEXP);
    Rcpp::traits::input_parameter< bool >::type Fagemode(FagemodeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ricker(use_rickerSEXP);
    Rcpp::traits::input_parameter< int >::type T_safe(T_safeSEXP);
    Rcpp::traits::input_parameter< int >::type gpu_threads(gpu_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(run_simulation_gpu(zr_w_dist, month_weights, W1_alk, agedata, harvest_params_in, growth_params_dd_in1, growth_params_dd_in2, survival_params, scenario_to_run, policy_combos, compliance_structure, before_policy_years, policy_years, lake_area_ha, initial_pop_size, rec_a, rec_b, rec_v, F_over_Z_ratio, juv_onlyM_len, spawn_month, recruit_entry_month, rep, vmonthly_avg, min_adult_age, age_recruit, age_spawn, psd_stock, psd_quality, psd_preferred, psd_memorable, psd_trophy, Fagemode, use_ricker, T_safe, gpu_threads));
    return rcpp_result_gen;
END_RCPP
}
// run_simulation_hybrid
List run_simulation_hybrid(NumericVector zr_w_dist, NumericVector month_weights, NumericMatrix W1_alk, NumericMatrix agedata, List harvest_params_in, List growth_params_dd_in1, List growth_params_dd_in2, List survival_params, List scenario_to_run, DataFrame policy_combos, DataFrame compliance_structure, IntegerVector cpu_combo_indices, IntegerVector gpu_combo_indices, int gpu_thread_count, int before_policy_years, int policy_years, double lake_area_ha, int initial_pop_size, double rec_a, double rec_b, double rec_v, double F_over_Z_ratio, double juv_onlyM_len, int spawn_month, int recruit_entry_month, int rep, double vmonthly_avg, double min_adult_age, double age_recruit, double age_spawn, double psd_stock, double psd_quality, double psd_preferred, double psd_memorable, double psd_trophy, bool Fagemode, bool use_ricker, int T_safe);
RcppExport SEXP _craibm_run_simulation_hybrid(SEXP zr_w_distSEXP, SEXP month_weightsSEXP, SEXP W1_alkSEXP, SEXP agedataSEXP, SEXP harvest_params_inSEXP, SEXP growth_params_dd_in1SEXP, SEXP growth_params_dd_in2SEXP, SEXP survival_paramsSEXP, SEXP scenario_to_runSEXP, SEXP policy_combosSEXP, SEXP compliance_structureSEXP, SEXP cpu_combo_indicesSEXP, SEXP gpu_combo_indicesSEXP, SEXP gpu_thread_countSEXP, SEXP before_policy_yearsSEXP, SEXP policy_yearsSEXP, SEXP lake_area_haSEXP, SEXP initial_pop_sizeSEXP, SEXP rec_aSEXP, SEXP rec_bSEXP, SEXP rec_vSEXP, SEXP F_over_Z_ratioSEXP, SEXP juv_onlyM_lenSEXP, SEXP spawn_monthSEXP, SEXP recruit_entry_monthSEXP, SEXP repSEXP, SEXP vmonthly_avgSEXP, SEXP min_adult_ageSEXP, SEXP age_recruitSEXP, SEXP age_spawnSEXP, SEXP psd_stockSEXP, SEXP psd_qualitySEXP, SEXP psd_preferredSEXP, SEXP psd_memorableSEXP, SEXP psd_trophySEXP, SEXP FagemodeSEXP, SEXP use_rickerSEXP, SEXP T_safeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type zr_w_dist(zr_w_distSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type month_weights(month_weightsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W1_alk(W1_alkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type agedata(agedataSEXP);
    Rcpp::traits::input_parameter< List >::type harvest_params_in(harvest_params_inSEXP);
    Rcpp::traits::input_parameter< List >::type growth_params_dd_in1(growth_params_dd_in1SEXP);
    Rcpp::traits::input_parameter< List >::type growth_params_dd_in2(growth_params_dd_in2SEXP);
    Rcpp::traits::input_parameter< List >::type survival_params(survival_paramsSEXP);
    Rcpp::traits::input_parameter< List >::type scenario_to_run(scenario_to_runSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type policy_combos(policy_combosSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type compliance_structure(compliance_structureSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cpu_combo_indices(cpu_combo_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gpu_combo_indices(gpu_combo_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type gpu_thread_count(gpu_thread_countSEXP);
    Rcpp::traits::input_parameter< int >::type before_policy_years(before_policy_yearsSEXP);
    Rcpp::traits::input_parameter< int >::type policy_years(policy_yearsSEXP);
    Rcpp::traits::input_parameter< double >::type lake_area_ha(lake_area_haSEXP);
    Rcpp::traits::input_parameter< int >::type initial_pop_size(initial_pop_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type rec_a(rec_aSEXP);
    Rcpp::traits::input_parameter< double >::type rec_b(rec_bSEXP);
    Rcpp::traits::input_parameter< double >::type rec_v(rec_vSEXP);
    Rcpp::traits::input_parameter< double >::type F_over_Z_ratio(F_over_Z_ratioSEXP);
    Rcpp::traits::input_parameter< double >::type juv_onlyM_len(juv_onlyM_lenSEXP);
    Rcpp::traits::input_parameter< int >::type spawn_month(spawn_monthSEXP);
    Rcpp::traits::input_parameter< int >::type recruit_entry_month(recruit_entry_monthSEXP);
    Rcpp::traits::input_parameter< int >::type rep(repSEXP);
    Rcpp::traits::input_parameter< double >::type vmonthly_avg(vmonthly_avgSEXP);
    Rcpp::traits::input_parameter< double >::type min_adult_age(min_adult_ageSEXP);
    Rcpp::traits::input_parameter< double >::type age_recruit(age_recruitSEXP);
    Rcpp::traits::input_parameter< double >::type age_spawn(age_spawnSEXP);
    Rcpp::traits::input_parameter< double >::type psd_stock(psd_stockSEXP);
    Rcpp::traits::input_parameter< double >::type psd_quality(psd_qualitySEXP);
    Rcpp::traits::input_parameter< double >::type psd_preferred(psd_preferredSEXP);
    Rcpp::traits::input_parameter< double >::type psd_memorable(psd_memorableSEXP);
    Rcpp::traits::input_parameter< double >::type psd_trophy(psd_trophySEXP);
    Rcpp::traits::input_parameter< bool >::type Fagemode(FagemodeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ricker(use_rickerSEXP);
    Rcpp::traits::input_parameter< int >::type T_safe(T_safeSEXP);
    rcpp_result_gen = Rcpp::wrap(run_simulation_hybrid(zr_w_dist, month_weights, W1_alk, agedata, harvest_params_in, growth_params_dd_in1, growth_params_dd_in2, survival_params, scenario_to_run, policy_combos, compliance_structure, cpu_combo_indices, gpu_combo_indices, gpu_thread_count, before_policy_years, policy_years, lake_area_ha, initial_pop_size, rec_a, rec_b, rec_v, F_over_Z_ratio, juv_onlyM_len, spawn_month, recruit_entry_month, rep, vmonthly_avg, min_adult_age, age_recruit, age_spawn, psd_stock, psd_quality, psd_preferred, psd_memorable, psd_trophy, Fagemode, use_ricker, T_safe));
    return rcpp_result_gen;
END_RCPP
}
// run_simulation_v2_cpp
List run_simulation_v2_cpp(NumericVector zr_w_dist, NumericVector month_weights, NumericMatrix W1_alk, NumericMatrix agedata, List harvest_params_in, List growth_params_dd_in1, List growth_params_dd_in2, List survival_params, List scenario_to_run, DataFrame policy_combos, DataFrame compliance_structure, int before_policy_years, int policy_years, double lake_area_ha, int initial_pop_size, double rec_a, double rec_b, double rec_v, double F_over_Z_ratio, double juv_onlyM_len, int spawn_month, int recruit_entry_month, int rep, double vmonthly_avg, double min_adult_age, double age_recruit, double age_spawn, double psd_stock, double psd_quality, double psd_preferred, double psd_memorable, double psd_trophy, bool Fagemode, bool use_ricker, int omp_nthreads, int gpu_threads, int T_safe);
RcppExport SEXP _craibm_run_simulation_v2_cpp(SEXP zr_w_distSEXP, SEXP month_weightsSEXP, SEXP W1_alkSEXP, SEXP agedataSEXP, SEXP harvest_params_inSEXP, SEXP growth_params_dd_in1SEXP, SEXP growth_params_dd_in2SEXP, SEXP survival_paramsSEXP, SEXP scenario_to_runSEXP, SEXP policy_combosSEXP, SEXP compliance_structureSEXP, SEXP before_policy_yearsSEXP, SEXP policy_yearsSEXP, SEXP lake_area_haSEXP, SEXP initial_pop_sizeSEXP, SEXP rec_aSEXP, SEXP rec_bSEXP, SEXP rec_vSEXP, SEXP F_over_Z_ratioSEXP, SEXP juv_onlyM_lenSEXP, SEXP spawn_monthSEXP, SEXP recruit_entry_monthSEXP, SEXP repSEXP, SEXP vmonthly_avgSEXP, SEXP min_adult_ageSEXP, SEXP age_recruitSEXP, SEXP age_spawnSEXP, SEXP psd_stockSEXP, SEXP psd_qualitySEXP, SEXP psd_preferredSEXP, SEXP psd_memorableSEXP, SEXP psd_trophySEXP, SEXP FagemodeSEXP, SEXP use_rickerSEXP, SEXP omp_nthreadsSEXP, SEXP gpu_threadsSEXP, SEXP T_safeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type zr_w_dist(zr_w_distSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type month_weights(month_weightsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W1_alk(W1_alkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type agedata(agedataSEXP);
    Rcpp::traits::input_parameter< List >::type harvest_params_in(harvest_params_inSEXP);
    Rcpp::traits::input_parameter< List >::type growth_params_dd_in1(growth_params_dd_in1SEXP);
    Rcpp::traits::input_parameter< List >::type growth_params_dd_in2(growth_params_dd_in2SEXP);
    Rcpp::traits::input_parameter< List >::type survival_params(survival_paramsSEXP);
    Rcpp::traits::input_parameter< List >::type scenario_to_run(scenario_to_runSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type policy_combos(policy_combosSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type compliance_structure(compliance_structureSEXP);
    Rcpp::traits::input_parameter< int >::type before_policy_years(before_policy_yearsSEXP);
    Rcpp::traits::input_parameter< int >::type policy_years(policy_yearsSEXP);
    Rcpp::traits::input_parameter< double >::type lake_area_ha(lake_area_haSEXP);
    Rcpp::traits::input_parameter< int >::type initial_pop_size(initial_pop_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type rec_a(rec_aSEXP);
    Rcpp::traits::input_parameter< double >::type rec_b(rec_bSEXP);
    Rcpp::traits::input_parameter< double >::type rec_v(rec_vSEXP);
    Rcpp::traits::input_parameter< double >::type F_over_Z_ratio(F_over_Z_ratioSEXP);
    Rcpp::traits::input_parameter< double >::type juv_onlyM_len(juv_onlyM_lenSEXP);
    Rcpp::traits::input_parameter< int >::type spawn_month(spawn_monthSEXP);
    Rcpp::traits::input_parameter< int >::type recruit_entry_month(recruit_entry_monthSEXP);
    Rcpp::traits::input_parameter< int >::type rep(repSEXP);
    Rcpp::traits::input_parameter< double >::type vmonthly_avg(vmonthly_avgSEXP);
    Rcpp::traits::input_parameter< double >::type min_adult_age(min_adult_ageSEXP);
    Rcpp::traits::input_parameter< double >::type age_recruit(age_recruitSEXP);
    Rcpp::traits::input_parameter< double >::type age_spawn(age_spawnSEXP);
    Rcpp::traits::input_parameter< double >::type psd_stock(psd_stockSEXP);
    Rcpp::traits::input_parameter< double >::type psd_quality(psd_qualitySEXP);
    Rcpp::traits::input_parameter< double >::type psd_preferred(psd_preferredSEXP);
    Rcpp::traits::input_parameter< double >::type psd_memorable(psd_memorableSEXP);
    Rcpp::traits::input_parameter< double >::type psd_trophy(psd_trophySEXP);
    Rcpp::traits::input_parameter< bool >::type Fagemode(FagemodeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ricker(use_rickerSEXP);
    Rcpp::traits::input_parameter< int >::type omp_nthreads(omp_nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type gpu_threads(gpu_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type T_safe(T_safeSEXP);
    rcpp_result_gen = Rcpp::wrap(run_simulation_v2_cpp(zr_w_dist, month_weights, W1_alk, agedata, harvest_params_in, growth_params_dd_in1, growth_params_dd_in2, survival_params, scenario_to_run, policy_combos, compliance_structure, before_policy_years, policy_years, lake_area_ha, initial_pop_size, rec_a, rec_b, rec_v, F_over_Z_ratio, juv_onlyM_len, spawn_month, recruit_entry_month, rep, vmonthly_avg, min_adult_age, age_recruit, age_spawn, psd_stock, psd_quality, psd_preferred, psd_memorable, psd_trophy, Fagemode, use_ricker, omp_nthreads, gpu_threads, T_safe));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_craibm_run_simulation_sizelimit_cpp", (DL_FUNC) &_craibm_run_simulation_sizelimit_cpp, 35},
    {"_craibm_detect_gpu_info", (DL_FUNC) &_craibm_detect_gpu_info, 0},
    {"_craibm_detect_openmp_info", (DL_FUNC) &_craibm_detect_openmp_info, 0},
    {"_craibm_run_simulation_gpu", (DL_FUNC) &_craibm_run_simulation_gpu, 36},
    {"_craibm_run_simulation_hybrid", (DL_FUNC) &_craibm_run_simulation_hybrid, 38},
    {"_craibm_run_simulation_v2_cpp", (DL_FUNC) &_craibm_run_simulation_v2_cpp, 37},
    {NULL, NULL, 0}
};

RcppExport void R_init_craibm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
