# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run IBM Simulation with Size Limits
run_simulation_sizelimit_cpp <- function(zr_w_dist, month_weights, W1_alk, agedata, harvest_params_in, growth_params_dd_in1, growth_params_dd_in2, survival_params, scenario_to_run, policy_combos, compliance_structure, before_policy_years = 50L, policy_years = 30L, lake_area_ha = 2818.635, initial_pop_size = 10000L, rec_a = 2.901, rec_b = 134.78, rec_v = 0.68, F_over_Z_ratio = 0.5, juv_onlyM_len = 130.0, spawn_month = 4L, recruit_entry_month = 8L, rep = 1L, vmonthly_avg = 0.15, min_adult_age = 1.0, age_recruit = 1.0, age_spawn = 1.0, psd_stock = 130.0, psd_quality = 200.0, psd_preferred = 250.0, psd_memorable = 300.0, psd_trophy = 380.0, Fagemode = FALSE, use_ricker = TRUE, T_safe = 0L) {
    .Call(`_craibm_run_simulation_sizelimit_cpp`, zr_w_dist, month_weights, W1_alk, agedata, harvest_params_in, growth_params_dd_in1, growth_params_dd_in2, survival_params, scenario_to_run, policy_combos, compliance_structure, before_policy_years, policy_years, lake_area_ha, initial_pop_size, rec_a, rec_b, rec_v, F_over_Z_ratio, juv_onlyM_len, spawn_month, recruit_entry_month, rep, vmonthly_avg, min_adult_age, age_recruit, age_spawn, psd_stock, psd_quality, psd_preferred, psd_memorable, psd_trophy, Fagemode, use_ricker, T_safe)
}

detect_gpu_info <- function() {
    .Call(`_craibm_detect_gpu_info`)
}

detect_openmp_info <- function() {
    .Call(`_craibm_detect_openmp_info`)
}

run_simulation_gpu <- function(zr_w_dist, month_weights, W1_alk, agedata, harvest_params_in, growth_params_dd_in1, growth_params_dd_in2, survival_params, scenario_to_run, policy_combos, compliance_structure, before_policy_years = 50L, policy_years = 30L, lake_area_ha = 2818.635, initial_pop_size = 10000L, rec_a = 2.901, rec_b = 134.78, rec_v = 0.68, F_over_Z_ratio = 0.5, juv_onlyM_len = 130.0, spawn_month = 4L, recruit_entry_month = 8L, rep = 1L, vmonthly_avg = 0.15, min_adult_age = 1.0, age_recruit = 1.0, age_spawn = 1.0, psd_stock = 130.0, psd_quality = 200.0, psd_preferred = 250.0, psd_memorable = 300.0, psd_trophy = 380.0, Fagemode = FALSE, use_ricker = TRUE, T_safe = 0L, gpu_threads = 0L) {
    .Call(`_craibm_run_simulation_gpu`, zr_w_dist, month_weights, W1_alk, agedata, harvest_params_in, growth_params_dd_in1, growth_params_dd_in2, survival_params, scenario_to_run, policy_combos, compliance_structure, before_policy_years, policy_years, lake_area_ha, initial_pop_size, rec_a, rec_b, rec_v, F_over_Z_ratio, juv_onlyM_len, spawn_month, recruit_entry_month, rep, vmonthly_avg, min_adult_age, age_recruit, age_spawn, psd_stock, psd_quality, psd_preferred, psd_memorable, psd_trophy, Fagemode, use_ricker, T_safe, gpu_threads)
}

run_simulation_hybrid <- function(zr_w_dist, month_weights, W1_alk, agedata, harvest_params_in, growth_params_dd_in1, growth_params_dd_in2, survival_params, scenario_to_run, policy_combos, compliance_structure, cpu_combo_indices, gpu_combo_indices, gpu_thread_count = 4L, before_policy_years = 50L, policy_years = 30L, lake_area_ha = 2818.635, initial_pop_size = 10000L, rec_a = 2.901, rec_b = 134.78, rec_v = 0.68, F_over_Z_ratio = 0.5, juv_onlyM_len = 130.0, spawn_month = 4L, recruit_entry_month = 8L, rep = 1L, vmonthly_avg = 0.15, min_adult_age = 1.0, age_recruit = 1.0, age_spawn = 1.0, psd_stock = 130.0, psd_quality = 200.0, psd_preferred = 250.0, psd_memorable = 300.0, psd_trophy = 380.0, Fagemode = FALSE, use_ricker = TRUE, T_safe = 0L) {
    .Call(`_craibm_run_simulation_hybrid`, zr_w_dist, month_weights, W1_alk, agedata, harvest_params_in, growth_params_dd_in1, growth_params_dd_in2, survival_params, scenario_to_run, policy_combos, compliance_structure, cpu_combo_indices, gpu_combo_indices, gpu_thread_count, before_policy_years, policy_years, lake_area_ha, initial_pop_size, rec_a, rec_b, rec_v, F_over_Z_ratio, juv_onlyM_len, spawn_month, recruit_entry_month, rep, vmonthly_avg, min_adult_age, age_recruit, age_spawn, psd_stock, psd_quality, psd_preferred, psd_memorable, psd_trophy, Fagemode, use_ricker, T_safe)
}

#' @export
run_simulation_v2_cpp <- function(zr_w_dist, month_weights, W1_alk, agedata, harvest_params_in, growth_params_dd_in1, growth_params_dd_in2, survival_params, scenario_to_run, policy_combos, compliance_structure, before_policy_years = 50L, policy_years = 30L, lake_area_ha = 2818.635, initial_pop_size = 10000L, rec_a = 2.901, rec_b = 134.78, rec_v = 0.68, F_over_Z_ratio = 0.5, juv_onlyM_len = 130.0, spawn_month = 4L, recruit_entry_month = 8L, rep = 1L, vmonthly_avg = 0.15, min_adult_age = 1.0, age_recruit = 1.0, age_spawn = 1.0, psd_stock = 130.0, psd_quality = 200.0, psd_preferred = 250.0, psd_memorable = 300.0, psd_trophy = 380.0, Fagemode = FALSE, use_ricker = TRUE, omp_nthreads = 1L, gpu_threads = 0L, T_safe = 0L) {
    .Call(`_craibm_run_simulation_v2_cpp`, zr_w_dist, month_weights, W1_alk, agedata, harvest_params_in, growth_params_dd_in1, growth_params_dd_in2, survival_params, scenario_to_run, policy_combos, compliance_structure, before_policy_years, policy_years, lake_area_ha, initial_pop_size, rec_a, rec_b, rec_v, F_over_Z_ratio, juv_onlyM_len, spawn_month, recruit_entry_month, rep, vmonthly_avg, min_adult_age, age_recruit, age_spawn, psd_stock, psd_quality, psd_preferred, psd_memorable, psd_trophy, Fagemode, use_ricker, omp_nthreads, gpu_threads, T_safe)
}

